/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MagumAmbulanceWlList {
    }
}
declare global {
    interface HTMLMagumAmbulanceWlListElement extends Components.MagumAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMagumAmbulanceWlListElement: {
        prototype: HTMLMagumAmbulanceWlListElement;
        new (): HTMLMagumAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "magum-ambulance-wl-list": HTMLMagumAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MagumAmbulanceWlList {
    }
    interface IntrinsicElements {
        "magum-ambulance-wl-list": MagumAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "magum-ambulance-wl-list": LocalJSX.MagumAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMagumAmbulanceWlListElement>;
        }
    }
}
